apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: parametrized-dice-roll-8
spec:
  tasks:
  - name: first
    taskRef:
      name: first-task
  - name: roll
    params: 
    - name: sides
      value: "8"
    taskRef:
      name: die-roll-param

